#!/usr/bin/env bash
#Install nginx web server
# Update package lists and install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
echo "server {
    listen 80;
    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default

# Create an HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart
