#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# Redirect /redirect_me to another page with a "301 Moved Permanently" response

# Update package lists and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a simple HTML file with "Hello World!" content
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Configure Nginx to listen on port 80 and serve the created HTML file
sudo sh -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.example.com/new_page; # Change this URL to the desired redirection destination
    }
}
EOF'

# Restart Nginx
sudo service nginx restart
