#!/usr/bin/env bash
# A Bash script prints Best School 10 times, then Hi after the 9th iteration.
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
