#!/usr/bin/env bash
# A Bash script prints Best School 10 times, then Hi after the 9th iteration.
for i in {1..10}
do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
done
