#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
i=0
x=0
while [ $x -le 12 ]
do
	echo "Hour: $i"
	m=1
	while [ $m -le 59 ]
	do
		echo $m
		((m++))
	done
	((i++))
	((x++))
done
