#!/usr/bin/env bash
# install the ufw firewall and setup a few rules
# Configure ufw so that it blocks all incoming traffic
# except the following TCP ports:
# 22 (SSH) / 443 (HTTPS SSL) / 80 (HTTP)

sudo apt-get update
sudo apt-get install ufw -y
sudo ufw status verbose
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
echo "y" | sudo ufw enable
sudo ufw status verbose
