#!/usr/bin/env bash
# Client configuration file
echo "Host 34.234.201.128" >> ~/.ssh/config
echo "    IdentityFile ~/.ssh/school" >> ~/.ssh/config
echo "    PasswordAuthentication no" >> ~/.ssh/config

